# Generated by Django 5.0.3 on 2024-04-14 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_app', '0005_companyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_cgpa', models.FloatField()),
                ('required_skills', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('cgpa', models.FloatField()),
                ('skills', models.CharField(max_length=255)),
                ('is_placed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('eligibility_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TPO_app.eligibilitycriteria')),
            ],
        ),
    ]
