# Generated by Django 5.0.3 on 2024-05-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_app', '0006_eligibilitycriteria_student_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(default='YourDefaultBranch', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='prn',
            field=models.IntegerField(default='YourDefaultBranch'),
        ),
    ]
