# Generated by Django 5.0.3 on 2024-05-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_app', '0009_alter_student_prn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='prn',
        ),
    ]
